### ISSUE TITLE
Full API

### ISSUE THREAD

**Issue by PrinceShubham05** [godownloader/tiktok-downloader#1]
How can i get full access to api without time limit or how can i create such type of api... your rapidapi link is not working pls fix that...

**Comment by godownloader** [comment]
Thank you for let me know. I have switched my api on RapidAPI to public. Please try a gain.
[https://rapidapi.com/godownloaderofficial/api/tiktok-download-video-no-watermark/](https://rapidapi.com/godownloaderofficial/api/tiktok-download-video-no-watermark/)

**Comment by PrinceShubham05** [comment]
Can i get free api without limit...

**Comment by godownloader** [comment]
> Can i get free api without limit...

Sorry there is no unlimited api .
If you want to download TikTok video free without limitation, please visit our website: https://godownloader.com/

**Comment by PrinceShubham05** [comment]
I want to make an app but the api is only allows 5 request per 30 mins

**Comment by godownloader** [comment]
> I want to make an app but the api is only allows 5 request per 30 mins

Sorry, I can't be of help to you about it. 
I'm going to close this issue, feel free to contact me at contact@godownloader.com if you need something else.
