### ISSUE TITLE
Set cache headers based on expiry time?

### ISSUE THREAD

**Issue by GitBoudewijn** [godownloader/tiktok-downloader#2]
Hello, thanks alot for this great api. However I noticed that you don't have any cache headers so if I request the exact same url 5 times I already reached the limit. So what if you set the `Cache-Control` and/or `Expires` response headers based on the expiry time of the response?

See this example:
`{"aweme_id":"6943631942512315654","author_cover":"https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/9df63fea7cb5c82ba03664410cd75b30~c5_1080x1080.webp?x-expires=1638212400&x-signature=oTrH6WdP4ix915ZCnVYPUVvMUxI%3D","desc":"#PEACHES @nickdemoura @jblazeofficial @godownloader","music_cover":"https://p16-sg.tiktokcdn.com/aweme/100x100/tos-alisg-v-2774/d64333443919413f8c8f48b3e2e76c9a.jpeg","music_author":"Justin Bieber","music_url":"https://sf16-ies-music-sg.tiktokcdn.com/obj/tos-alisg-ve-2774/c3dc1923163645dcacc7b49b26b68135","video_animated_cover":"https://p16-sign-va.tiktokcdn.com/obj/tos-maliva-p-0068/f5be0152d3e347ffbefe9e9d2732d8fc_1616690301?x-expires=1638147600&x-signature=PcOsdT%2B8oI5rO6mEdw7CH6n1tAE%3D","video_origin_cover":"https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068/170782ef7b4a4d86966b857bc8699ba9_1616690300~tplv-tiktokx-360p.webp?x-expires=1638147600&x-signature=xagdf4jqXFBDKA7cOQoUrE6k3D0%3D","video_no_watermark":"https://v77.tiktokcdn.com/901f87ba418c89dbc341d19c44d8c524/61a42e2e/video/tos/useast2a/tos-useast2a-ve-0068c003/1d68a42b175745369b5dafa5d6c1b1ce/?a=1180&br=3020&bt=1510&cd=0%7C0%7C0&ch=0&cr=3&cs=0&cv=1&dr=0&ds=6&er=&ft=xo5iS447gX.Inz7T&l=202111281934150102452421171CF3CB14&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=MzhvZXd2eHRlNDMzZjczM0ApOjZlNGQ0NGVnNzg4aGY0ZmdeL29tZm5nbGJgLS0vMTZzcy02LmMzYjBjNS8zXzQzYF46Yw%3D%3D&vl=&vr=","video_watermark":"https://v77.tiktokcdn.com/b883ad2507275a48fdc3161d88b64939/61a42e2e/video/tos/useast2a/tos-useast2a-ve-0068c002/47f2e70743ad4eb99aba4ec4d844b55d/?a=1180&br=3266&bt=1633&cd=0%7C0%7C0&ch=0&cr=3&cs=0&cv=1&dr=0&ds=3&er=&ft=xo5iS447gX.Inz7T&l=202111281934150102452421171CF3CB14&lr=all&mime_type=video_mp4&net=0&pl=0&qs=0&rc=MzhvZXd2eHRlNDMzZjczM0ApZ2U2ZTdoOzs6N2Q5ZTZlNWdeL29tZm5nbGJgLS0vMTZzcy5hYDFhXi4tYTZjLzYyMDI6Yw%3D%3D&vl=&vr="}`

Here's the information from this response:
`author_cover` has `x-expires=1638212400` (but this is longer than the rest).
`video_animated_cover` and `video_origin_cover` have `x-expires=1638147600`.
`video_no_watermark` and `video_watermark` have `/61a42e2e/` (1638149678 in base 16).

So as you can see the second is the shortest, althought you could also just compare all of them and select the shortest. You can then set the cache response headers to 10 or 5 minutes before this time. (Obviously you should only set the headers if you actually respond with the requested video and not with the default response).

Thanks!

**Comment by godownloader** [comment]
Thank you for your suggestion.
I set the cache response headers time to 2 minutes for now, will improve in the future.

**Comment by GitBoudewijn** [comment]
Hey,

I see you have `Cache-Control: max-age=120` on _api.godownloader.com/info_ but what I meant was adding it to _godownloader.com/api/tiktok-no-watermark-free_ (and the RapidApi one).

_api.godownloader.com/info_ uses POST so caching doesn't work there.

**Comment by godownloader** [comment]
> Hey,
> 
> I see you have `Cache-Control: max-age=120` on _api.godownloader.com/info_ but what I meant was adding it to _godownloader.com/api/tiktok-no-watermark-free_ (and the RapidApi one).
> 
> _api.godownloader.com/info_ uses POST so caching doesn't work there.

The free api is used for trial purpose only. Please do not use it for the production and try our api on RapidApi instead.
Thank you.

**Comment by GitBoudewijn** [comment]
> > Hey,
> > I see you have `Cache-Control: max-age=120` on _api.godownloader.com/info_ but what I meant was adding it to _godownloader.com/api/tiktok-no-watermark-free_ (and the RapidApi one).
> > _api.godownloader.com/info_ uses POST so caching doesn't work there.
> 
> The free api is used for trial purpose only. Please do not use it for the production and try our api on RapidApi instead. Thank you.

Yeah I'm using it like that (I don't have any production). It's just that every time you refresh it makes the same request again and takes away from the rate limit (which is unnecessary).

**Comment by godownloader** [comment]
> > > Hey,
> > > I see you have `Cache-Control: max-age=120` on _api.godownloader.com/info_ but what I meant was adding it to _godownloader.com/api/tiktok-no-watermark-free_ (and the RapidApi one).
> > > _api.godownloader.com/info_ uses POST so caching doesn't work there.
> > 
> > 
> > The free api is used for trial purpose only. Please do not use it for the production and try our api on RapidApi instead. Thank you.
> 
> Yeah I'm using it like that (I don't have any production). It's just that every time you refresh it makes the same request again and takes away from the rate limit (which is unnecessary).

I've updated the cache-control for the free api also. 
Thank you so much for the suggestion 🙏🏻🙏🏻🙏🏻
